### ISSUE TITLE
instruction on how to build / run it

### ISSUE THREAD

**Issue by fsperling** [jaspervdj/lorem-markdownum#12]
Hey,
I tried to run the HTTP API on my machine but I couldn't figure out how to build and/or run it.
Could you provide a release or instructions how to build and run it?

Cheers,
Felix

**Comment by jaspervdj** [comment]
Thanks for bringing this up!  I added instructions to the README here: https://github.com/jaspervdj/lorem-markdownum#building-and-running-from-source

**Comment by fsperling** [comment]
Awesome! That helped me a lot (it's also my first Haskell project).
I did have to change the resolver in stack.yaml to: lts-14.27
As there seems to be no lts-15.x available anymore: https://github.com/commercialhaskell/lts-haskell

**Comment by jaspervdj** [comment]
Sounds good -- FWIW, I bumped it to a more recent version here: https://github.com/jaspervdj/lorem-markdownum/commit/338c5f10e40497c3825169596bc0e3ffff16def8
