### ISSUE TITLE
Down ?

### ISSUE THREAD

**Issue by Corantin** [jaspervdj/lorem-markdownum#13]
![image](https://user-images.githubusercontent.com/13890618/191629565-ddd4da3b-780c-4dbc-9954-76971e2821e0.png)

**Comment by jaspervdj** [comment]
Thanks for the ping!  Should be back up now.

**Comment by Corantin** [comment]
<3

**Comment by Corantin** [comment]
Do you plan to make an npm package? I would be really fan :p
