### ISSUE TITLE
Optionally don't split paragraphs

### ISSUE THREAD

**Issue by Sirtea** [jaspervdj/lorem-markdownum#5]
Hi,

I've been using this tool to generate content in a fake Ghost instance (where I develop themes).

As it turns out, Ghost renders paragraphs with newlines as <br /> (this is not the normal markdown specification), so it's kind of ugly, and fixing manually defeats the purpose of a markdown generator...

¿Should be possible to add an advanced setting, so the lines belonging to the same <p> are not broken on different lines?

Thanks

**Comment by jaspervdj** [comment]
Sounds good.  I added a `no-wrapping` option.

**Comment by Sirtea** [comment]
Hi,

A curl works fine:
`curl 'https://jaspervdj.be/lorem-markdownum/markdown.txt?no-wrapping=on'`

Webpage is still splitting paragraphs, although it have a no-wrapping option (<https://jaspervdj.be/lorem-markdownum/>).

This saves the day, though.

Thanks!

**Comment by jaspervdj** [comment]
On the web-page, you need to re-generate markdown (`Generate me some markdown!`) after changing the settings.
