### ISSUE TITLE
Request for no-external-link parameter

### ISSUE THREAD

**Issue by CMeza99** [jaspervdj/lorem-markdownum#7]

**Comment by jaspervdj** [comment]
What would this option do?  Generate only links to anchors, e.g. `[foo](#bar)`?  Should these anchors exist?

**Comment by floorish** [comment]
This might be a good idea, I just got the following paragraph:

```markdown
Odio manu dabimus petebant molimine valeant. Victi ex capillos, aevo uda habet
furentibus natus, corpora in porrexit quaerit **respersit** quod quem quoque.
Initis rebus amplexus accipitris referebat opus in [vittam](h t t p : / / s e x . c o m /)
abest.
```

Kind of funny, but luckily I only used it on my local machine :)
Non-existing anchors would be perfect in this case.

**Comment by jaspervdj** [comment]
Ah, those naughty latin words!

Generating non-existing anchor links is easy, but it could still generate stuff like `[lipsum](#sex)`.

Better would be to first generate the headers and then create anchors based on that, but that would require changing the code structure a little.

**Comment by floorish** [comment]
I wouldn't mind `[lipsum](#sex)`, since an accidental click on that link won't show anything nsfw.

And if you generate headers first, you'll have the same problem right?

**Comment by jaspervdj** [comment]
This parameter is now included... better late than never?
