### ISSUE TITLE
Enable Cross-Origin Access

### ISSUE THREAD

**Issue by yassh** [jaspervdj/lorem-markdownum#8]
I tried to access HTTP API by [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), then failed. Browser displayed following error message in the console.

> Failed to load https://jaspervdj.be/lorem-markdownum/markdown.txt: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by jaspervdj** [comment]
I've added the header, it should work now?

**Comment by yassh** [comment]
Yes, it works! Thank you!
